// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_xdgRhI5G3ActKD76pCBFi3nkH6kHNpQ',
    appId: '1:965314703398:web:869b2fb1dc50f5e3eef6e7',
    messagingSenderId: '965314703398',
    projectId: 'chatapp-bdcc0',
    authDomain: 'chatapp-bdcc0.firebaseapp.com',
    storageBucket: 'chatapp-bdcc0.firebasestorage.app',
    measurementId: 'G-W9TJGFZG4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEy6NbWfogI-1r_9ymDyRBCLOsDmA9jKU',
    appId: '1:965314703398:android:bfab0da4563c5039eef6e7',
    messagingSenderId: '965314703398',
    projectId: 'chatapp-bdcc0',
    storageBucket: 'chatapp-bdcc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm4BUCjZSZFV6HnNmUfxC6FOxG7LmkYks',
    appId: '1:965314703398:ios:9a61e388d3030247eef6e7',
    messagingSenderId: '965314703398',
    projectId: 'chatapp-bdcc0',
    storageBucket: 'chatapp-bdcc0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm4BUCjZSZFV6HnNmUfxC6FOxG7LmkYks',
    appId: '1:965314703398:ios:9a61e388d3030247eef6e7',
    messagingSenderId: '965314703398',
    projectId: 'chatapp-bdcc0',
    storageBucket: 'chatapp-bdcc0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_xdgRhI5G3ActKD76pCBFi3nkH6kHNpQ',
    appId: '1:965314703398:web:1a0d78a7502685dbeef6e7',
    messagingSenderId: '965314703398',
    projectId: 'chatapp-bdcc0',
    authDomain: 'chatapp-bdcc0.firebaseapp.com',
    storageBucket: 'chatapp-bdcc0.firebasestorage.app',
    measurementId: 'G-DYFD3EHKP4',
  );
}
